### ISSUE TITLE
Brush Mode Replace's Value is reset when selecting a different node.

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#10]
On a node with a Node Painter component:
- Set the Brush Mode to Replace
- Change value to anything besides 1
- Click another node in the TC2 window
- Click back to the Node Painter node

The value of Value is reset to 1.  Size and Intensity maintain their values if changed.

**Comment by Seneral** [comment]
Fixed by storing these values in the main painting class, not the editor.
