### ISSUE TITLE
Beta 1.1 Replace does not respect Value

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#11]
Replace adds instead of clamping to Value. 

The image shows a trailing peak which happens if you select Replace and no matter the value just click and hold in one spot.

![replace](https://cloud.githubusercontent.com/assets/27040/23575225/9c2bbac4-003e-11e7-96ea-136244f3b79b.png)

**Comment by Seneral** [comment]
True - will figure that out!

**Comment by Seneral** [comment]
Fixed in beta 1.2!
