### ISSUE TITLE
Sort order on brushes is AlphaNumeric instead of numeric.

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#13]
This could be intentional, but if the user wants more than 9 brushes.  They'll have to rename the existing brushes by adding zeroes or something to the front of the file names.

It might be a good idea to split the filename at the first underscore and convert the first part to a number for sorting.

![brush_order](https://cloud.githubusercontent.com/assets/27040/23575516/4fa22c2a-0042-11e7-9c5c-b7617adf4bab.png)

**Comment by Seneral** [comment]
Good idea, thanks!

**Comment by Seneral** [comment]
Is implemented
