### ISSUE TITLE
Need documentation on shortcut and modifier keys

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#18]
Can you update the documentation to include shortcuts and modifiers?

For example to change the Size (Ctrl+scrollwheel) and Intensity (Shift+scrollwheel) of a brush.  Having tooltips displayed would be a good alternative.

Can you also add a modifier for Replace and Lerps' Target, maybe Ctrl+Shift+scrollwheel?

**Comment by Seneral** [comment]
Yes, will mention them in the docs and also will have the keys adjustable in the Settings if possible:)

**Comment by Seneral** [comment]
Documentation in planning and added both shortcuts - tab to switch to last brush and Control+Shift+ScrollWheel to change target/smoothen bias value (Tab+ScrollWheel was not applicable, could not get it to work without nasty hacks - also that would case interference with switching to last brush).
