### ISSUE TITLE
Add a way to rotate the brush

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#19]
Add a way to rotate the brush.  This would be very useful it in getting the most out of a brush and breaking up detail.  Having a shortcut key would also be nice.

**Comment by Seneral** [comment]
Yes, would be handy - and actually needed, considering #21

**Comment by Seneral** [comment]
Added way to rotate brush by holding space and scrolling - also, transformation of the nodes has been fixed and now follow only the object the NodePainter script is attached to.
