### ISSUE TITLE
Brush presets (show which is active)

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#2]
When selecting a brush preset, it would be nice to highlight the current one. 

Also, when creating 10 or more presets the number is not displayed.

How do you delete a preset?

**Comment by Seneral** [comment]
Will implement highlight until you change the brush value again (presets are copied in, not referenced).
Also, numbering bug confirmed. May need a layout change for that...

You can delete a preset by right-clicking and selecting delete from the context menu that pops up:)

**Comment by geekrelief** [comment]
What do you think about showing the presets as images instead of numbers?  Kind of like how colors presets show colors, having a mini image would help.  Of course if that's too troublesome to implement for now, I understand. :)

**Comment by Seneral** [comment]
Would love that, but I suspect that won't help much - the buttons are like 20px in size...
And making them bigger is not an option.

**Comment by Seneral** [comment]
Set for a later beta as it's not very critical

**Comment by Seneral** [comment]
Done, but it will reset after changing a brush-value and will not reappear when the settings again match a preset (could cause confusion).
