### ISSUE TITLE
When the terrain is rotated, the brush painting / preview doesn't match.

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#21]
This is probably the same issue Antonio was talking to you about.  Similarly scaling is not working.
![rotation doesn t affect brush](https://cloud.githubusercontent.com/assets/27040/23593356/b623fed4-01c2-11e7-81c6-4857803af51c.gif)

![scale not maintained](https://cloud.githubusercontent.com/assets/27040/23593456/f832a040-01c3-11e7-8b8a-95efe4f0fe20.gif)

**Comment by Seneral** [comment]
This goes hand in hand with #19
And scaling reset is also confirmed :)

**Comment by Seneral** [comment]
Will only leave #19 open:)

**Comment by Seneral** [comment]
Both transformation issues fixed.
