### ISSUE TITLE
Add error messages if the Resource Folder or Cache Folder does not have a valid path.

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#23]
If the Resource Folder is not valid, the Node Painter breaks because a Directory Not Found Exception is thrown from GlobalPainting.cs Line 45.  

`string[] texPaths = Directory.GetFiles (texFolder);`

This exception should be caught so the inspector editor can render an error message to tell the user to locate the Resources Folder.

Likewise a check should be done for the Cache Folder.

The Settings should check the folders and display an error box if the paths are not valid.

**Comment by Seneral** [comment]
Fixed:)
