### ISSUE TITLE
When multiple scene tabs are open painting breaks

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#26]
https://streamable.com/sb74e

**Comment by Seneral** [comment]
Having two open at the same time caused the painting to be interrupted once the second view came to render - this is fixed. The artifacts with randomly appearing GUI is still unresolved though.

**Comment by Seneral** [comment]
Fixed that aswell - and not only in that case, but finally always, all GUI artifacts should be gone now:)
