### ISSUE TITLE
Brush Preview missing in Scene and Canvas preview

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#27]
![scene preview missing](https://cloud.githubusercontent.com/assets/27040/23877012/7c189a1a-07fd-11e7-98e1-a9a6a0ee9318.gif)

**Comment by geekrelief** [comment]
This is related to #29.  Even if you fix the Resource Folder location, the brush preview doesn't load up.

**Comment by Seneral** [comment]
Fixed along with #29 - preview now refreshes when the paths are fixed:)
