### ISSUE TITLE
Define terms in a Glossary

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#30]
It would be helpful to define terms used in the docs.  For example a glossary for terms like:

NodePainter (script) - The script used to map Canvas data to a TC2 node.  It is possible to map the Canvas data to multiple nodes using Node Targets.  For example when you want to paint biomes, you can attach the script to a gameObject outside of the TC2 node hierarchy and specify multiple Nodes for mapping.
Biome - A biome is a grouping of flora and fauna for a habitat like a forest, tundra, or desert.  With Node Painter, you can group splat, trees, grass, etc into a biome using a Multi Channel Canvas and the Node Targets setting.  Each color in a Multi Channel Canvas can represent a biome for your terrain.  See the BiomePainting example.
Canvas - The buffer used for painting data that is mapped to one or multiple TC2 nodes.  Data in a canvas can be used to paint height, textures or masks.

**Comment by Seneral** [comment]
Good points - although I don't want to get too generic with the terms (biome in particular).
Also, most of that definition is going to be obsolete with an upcoming TC2 update which allows to group biomes into seperate terrain groups either way:)
But I'll add something like this, thanks:)

**Comment by geekrelief** [comment]
Yeah with regards to biome that's fine.  But you just want to avoid using jargon that's be altered.  With respect to biome it has a specific definition, so I wanted to show how it's used with respect to NodePainter, and its connection to MultiChannel painting.

**Comment by Seneral** [comment]
Yes, makes sense:)
Will concentrate on getting ready for release first:)

**Comment by Seneral** [comment]
Now added and live:)
