### ISSUE TITLE
Is Multi Channel Canvas missing Modifications?

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#32]
Maybe it's just my beta version, but is the Multi channel Canvas missing the Modifications region?

I see it in your screenshot, but not in my beta.

**Comment by geekrelief** [comment]
Also I see in your screenshot you have textures for your channels whereas I have solid colors.

**Comment by Seneral** [comment]
Hehe:)
Yes, for now I don't have modifications for Multi-Mask format, and I honestly don't know if I will / if that even makes sense.
Do you think there should be?
Well if you use the format for anything other than masks, maybe. But it also has technical problems, adding modifications (atleast those that apply to multiple/all channels) would mean I have to add another pass to EACH canvas texture while modifying...

**Comment by geekrelief** [comment]
Well if you want height node targets it would be a quick way to adjust the height of a biome.  That's pretty much the only reason I use modifications at the moment.  Maybe it's not necessary.  I'll have to experiment more.

**Comment by Seneral** [comment]
Well usually when painting it is a mask - when you want to change what you paint (like the height of the biome) you change the selector nodes the mask apply to or similar - but you usually do not modify the canvas itself, as it only holds information about what is actually there. Besides, it would be technically incompatible with the canvas normalization, atleast in the way you suggested to use it....

**Comment by geekrelief** [comment]
Yeah, good points. I'll close this for now.
