### ISSUE TITLE
Feature Suggestion: Color bar below channel

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#33]
When using a Texture Preview add a small rect below the image with the color of the channel. 
![color_channel](https://cloud.githubusercontent.com/assets/27040/24121559/eb3f373c-0d75-11e7-8207-14875f4cc66c.png)

**Comment by Seneral** [comment]
Yes, have thought about something similar (like square in the top right corner).
Bar sounds prettier though - Will definitely do that, so it's easier to match the colors in the preview to the channels:)

**Comment by Seneral** [comment]
Implemented in the upcoming Update 1.1:)
