### ISSUE TITLE
Losing paint job

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#36]
I'm not sure what's the exact cause, but after a while of painting and manipulating stuff I run into this error and my paint job disappears.

InvalidOperationException: This cannot be used during play mode.
UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty (Scene scene) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorSceneManagerBindings.gen.cs:165)
TerrainComposer2.NodePainter.NodePainter.AssignCanvas (UnityEngine.RenderTexture[] textures) (at Assets/Plugins/Node Painter/Scripts/Core/NodePainter.cs:122)
TerrainComposer2.NodePainter.Painting.AssignAllCanvas (UnityEngine.RenderTexture[] tex) (at Assets/Plugins/Node Painter/Scripts/Core/Painting.cs:442)
TerrainComposer2.NodePainter.Painting.AssignModCanvas (System.Collections.Generic.List`1 RTs, UnityEngine.RenderTexture modTex) (at Assets/Plugins/Node Painter/Scripts/Core/Painting.cs:434)
TerrainComposer2.NodePainter.Painting.AssignModCanvas (UnityEngine.RenderTexture modTex) (at Assets/Plugins/Node Painter/Scripts/Core/Painting.cs:420)
TerrainComposer2.NodePainter.Painting.PushContent (UnityEngine.RenderTexture curTexFrame, UnityEngine.RenderTexture blendTex) (at Assets/Plugins/Node Painter/Scripts/Core/Painting.cs:1492)
TerrainComposer2.NodePainter.Painting.PushContent () (at Assets/Plugins/Node Painter/Scripts/Core/Painting.cs:1457)
TerrainComposer2.NodePainter.Painting.ImportTexture (System.Collections.Generic.List`1 tex, Int32 channelCount, Boolean adaptSpecs, Format format) (at Assets/Plugins/Node Painter/Scripts/Core/Painting.cs:672)
TerrainComposer2.NodePainter.Painting.ImportTexture (UnityEngine.Texture2D tex, Boolean adaptSpecs, Format format) (at Assets/Plugins/Node Painter/Scripts/Core/Painting.cs:638)
TerrainComposer2.NodePainter.Painting.ImportCanvas (System.String path, Format format, Int32 channelCount, Int32 sizeX, Int32 sizeY) (at Assets/Plugins/Node Painter/Scripts/Core/Painting.cs:1057)
TerrainComposer2.NodePainter.Painting.LoadLastSession () (at Assets/Plugins/Node Painter/Scripts/Core/Painting.cs:889)
TerrainComposer2.NodePainter.Painting.Open () (at Assets/Plugins/Node Painter/Scripts/Core/Painting.cs:286)
TerrainComposer2.NodePainter.NodePainter.OnEnable () (at Assets/Plugins/Node Painter/Scripts/Core/NodePainter.cs:89)

**Comment by geekrelief** [comment]
I'm using multiple tiles 5x5 of 128x128 each.  And on occasion I'm hiding some of the tiles.

**Comment by geekrelief** [comment]
I'm also getting a quite a few of these errors.  I wonder if it's related.

IndexOutOfRangeException: Array index is out of range.
TerrainComposer2.TC_Generate.ComputeHeight (Rect generateRect) (at Assets/Plugins/TerrainComposer2/Scripts/Generate/TC_Generate.cs:1048)
TerrainComposer2.TC_Generate.Compute (Int32 outputId, Rect generateRect) (at Assets/Plugins/TerrainComposer2/Scripts/Generate/TC_Generate.cs:237)
TerrainComposer2.TC_Generate.RunGenerateStack () (at Assets/Plugins/TerrainComposer2/Scripts/Generate/TC_Generate.cs:229)
TerrainComposer2.TC_Generate.MyUpdate () (at Assets/Plugins/TerrainComposer2/Scripts/Generate/TC_Generate.cs:187)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:249)

**Comment by Seneral** [comment]
Well the error is fixed in the release version, so when it's really related to loosing the paint job then it's fixed already:)
The last one is some kind of precision error on my side that I have to figure out... it's related to the partial generation update, that's for sure.
