### ISSUE TITLE
Brush Mode: Replace with value of 0 breaks the canvas.

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#7]
I'm trying to create a basin in the terrain.

1. In the TC2 window, create a layer with Noise.
2. Add a mask Node.
3. Add Node Painter component to the mask node.
4. Create a canvas, and change Modifications Brightness to 1 and Apply.
5. Set the Brush Mode to Replace, Value 0.
6. Paint and the canvas is broken.

**Comment by Seneral** [comment]
Still, can't reproduce. Works perfectly fine for me.... will contact you on skype, maybe we can do a screenshare to see why it's not working for you:)

**Comment by geekrelief** [comment]
In Beta 1.1 Replace does not respect Value see #11.

**Comment by geekrelief** [comment]
This works as of Beta 1.2
