### ISSUE TITLE
Importing png produces acne around edges

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#9]
Exported png: 
![exported](https://cloud.githubusercontent.com/assets/27040/23540949/2f9b92da-ff99-11e6-8854-46bd31b92d27.png)

Imported png: 
![imported](https://cloud.githubusercontent.com/assets/27040/23540954/3665bc9e-ff99-11e6-84de-7c8709b4fd90.png)

Changing the texture settings doesn't make a difference.  Using the include brushes also produces acne around the edges.

**Comment by Seneral** [comment]
That's the fault of the format - PNG is only 8Bit (or atleast unity only supports 8Bit pngs) so the quality will suffer.
I recommend using raw, which is generally used for terrain and can also directly be loaded into a terrain if desired.
